//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinaryClinic.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public Nullable<int> pet_id { get; set; }
        public Nullable<System.DateTime> assignment_date { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Pets Pets { get; set; }
    }
}
